import type { AstroComponent } from "@lucide/astro";
import {
  Activity,
  Award,
  Biohazard,
  Bitcoin,
  Brain,
  Briefcase,
  Church,
  CircleQuestionMark,
  Clapperboard,
  CloudLightning,
  Coins,
  Cpu,
  Crown,
  FlaskConical,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  Handshake,
  HeartPulse,
  Landmark,
  MessageCircle,
  Music,
  Percent,
  Plane,
  Rocket,
  ScrollText,
  Ship,
  Sigma,
  Smartphone,
  Sparkles,
  Swords,
  Thermometer,
  TrendingUp,
  Trophy,
  UserMinus,
  Vote,
} from "@lucide/astro";

const subjects: readonly (readonly [RegExp, AstroComponent])[] = [
  [/\b(bitcoin|btc)\b/i, Bitcoin],
  [/\b(spacex|starship|nasa|lunar|mars|rockets?|orbit|satellites?|astronauts?|aliens?|ufo|uap|artemis)\b/i, Rocket],
  [/\b(ethereum|eth|solana|sol|xrp|ripple|dogecoin|doge|bnb|cardano|tokens?|tge|fdv|airdrop|stablecoin|memecoin|crypto|blockchain|defi|nft|binance|coinbase|hyperliquid|pump\.fun)\b/i, Coins],
  [/\b(fed|fomc|rate (cuts?|hikes?|decision)|interest rates?|inflation|cpi|recession|gdp|unemployment)\b/i, Percent],
  [/\b(oil|crude|wti|brent|opec|pipeline|gasoline|natural gas|lng)\b/i, Fuel],
  [/\b(gold|silver|copper|platinum)\b/i, Gem],
  [/\b(ipo|valuation|market cap|largest company|stocks?|shares|earnings|nasdaq|s&p 500|dow jones|all[- ]time high)\b/i, TrendingUp],
  [/\b(ai|agi|llm|gpt(-\d+)?|chatgpt|claude|gemini|grok|llama|deepseek|models?|arena|openai|anthropic|xai|deepmind)\b/i, Brain],
  [/\b(iphone|apple|android|pixel|foldable|smartphone|vision pro|headset|hardware product)\b/i, Smartphone],
  [/\b(gta|grand theft auto|nintendo|playstation|xbox|steam|video ?games?|esports?|fortnite|minecraft)\b/i, Gamepad2],
  [/\b(chips?|semiconductors?|tsmc|intel|software|app store|cybersecurity|hack(ed|ers)?|outage|quantum)\b/i, Cpu],
  [/\b(movies?|films?|box office|gross|trailer|opening weekend|oscars?|academy award|james bond|netflix|disney|marvel|sequel|premiere|rotten tomatoes)\b/i, Clapperboard],
  [/\b(album|songs?|concert|tour|grammys?|billboard|spotify|performs?|eurovision|halftime)\b/i, Music],
  [/\b(tweets?|posts?|twitter|truth social|instagram|youtube|tiktok|subscribers|followers)\b/i, MessageCircle],
  [/\b(pandemic|virus|outbreak|ebola|measles|hantavirus|covid|h5n1|bird flu)\b/i, Biohazard],
  [/\b(vaccines?|fda|cancer|disease|drugs?|health|hospital|ozempic)\b/i, HeartPulse],
  [/\b(earthquakes?|volcano|tsunami)\b/i, Activity],
  [/\b(hurricanes?|tornado|storms?|typhoon|cyclone|wildfires?|floods?)\b/i, CloudLightning],
  [/\b(temperature|degrees|weather|hottest|coldest|heat ?wave|climate)\b/i, Thermometer],
  [/\b(millennium prize|theorem|conjecture|proof|mathematic)/i, Sigma],
  [/\b(shipping|tankers?|vessels?|ships?|ports?|canal|strait|hormuz)\b/i, Ship],
  [/\b(airspace|flights?|airlines?|airports?|boeing|airbus|planes?|jets?)\b/i, Plane],
  [/\b(convicted|conviction|verdict|guilty|acquitted|sentenced?|arrested|indicted|indictment|charged|trial|court|scotus|ruling|lawsuit|pardon|extradited|prison)\b/i, Gavel],
  [/\b(ceasefire|peace (talks|deal|agreement)|truce|summit|meets?|meeting|visits?|deal signed|agreement|treaty|diplomatic|talks|negotiat)/i, Handshake],
  [/\b(invade|invasion|military|war|troops|strikes?|airstrikes?|missiles?|nuclear|nato|army|forces|attacks?|clash|captures?|enters?|blockade|siege|drones?|bombs?|hostages?|conflict|occupied|mobili[sz]ation|targets?|control)\b/i, Swords],
  [/\b(head of state|leader of|regime|coup|ruler|dictator)\b/i, Crown],
  [/\b(out (as|before|by)|resigns?|resignation|impeach(ed|ment)?|removed|steps? down|ousted|fired|dismissed)\b/i, UserMinus],
  [/\b(elections?|nominees?|nomination|primary|primaries|midterms?|senate|house|congress|seats?|governor|mayor|ballot|referendum|votes?|voting|polls?|balance of power|presidential|prime minister|chancellor|party)\b/i, Vote],
  [/\b(act|bill|signed into law|law|legislation|executive order|banned|regulation|tariffs?)\b/i, ScrollText],
  [/\b(pope|papal|conclave|jesus|christ|vatican|church|rapture|bible)\b/i, Church],
  [/\b(mvp|championship|champion|super bowl|world cup|nba|nfl|mlb|nhl|ufc|f1|formula 1|olympics?|grand slam|wimbledon|vs\.?|match|tournament|playoffs?|finals|cup|league|fight|boxing|medal)\b/i, Trophy],
  [/\b(emmys?|golden globes?|person of the year|nobel|awards?)\b/i, Award],
];

const categories: Readonly<Record<string, AstroComponent>> = {
  Politics: Landmark,
  World: Globe,
  Crypto: Coins,
  Business: Briefcase,
  Technology: Cpu,
  Science: FlaskConical,
  "Pop Culture": Sparkles,
};

export const marketIcon = ({ question, category }: { question: string; category?: string }): AstroComponent =>
  subjects.find(([pattern]) => pattern.test(question))?.[1] ?? categories[category ?? ""] ?? CircleQuestionMark;
