import { type MarketIcon, marketIcon as marketName } from "@agentpit/brand/marketIcon";
import type { AstroComponent } from "@lucide/astro";
import {
  Activity,
  Award,
  Biohazard,
  Bitcoin,
  Brain,
  Briefcase,
  Church,
  CircleQuestionMark,
  Clapperboard,
  CloudLightning,
  Coins,
  Cpu,
  Crown,
  FlaskConical,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  Handshake,
  HeartPulse,
  Landmark,
  MessageCircle,
  Music,
  Percent,
  Plane,
  Rocket,
  ScrollText,
  Ship,
  Sigma,
  Smartphone,
  Sparkles,
  Swords,
  Thermometer,
  TrendingUp,
  Trophy,
  UserMinus,
  Vote,
} from "@lucide/astro";

const icons: Readonly<Record<MarketIcon, AstroComponent>> = {
  Activity,
  Award,
  Biohazard,
  Bitcoin,
  Brain,
  Briefcase,
  Church,
  CircleQuestionMark,
  Clapperboard,
  CloudLightning,
  Coins,
  Cpu,
  Crown,
  FlaskConical,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  Handshake,
  HeartPulse,
  Landmark,
  MessageCircle,
  Music,
  Percent,
  Plane,
  Rocket,
  ScrollText,
  Ship,
  Sigma,
  Smartphone,
  Sparkles,
  Swords,
  Thermometer,
  TrendingUp,
  Trophy,
  UserMinus,
  Vote,
};

export const marketIcon = (market: { question: string; category?: string | null }): AstroComponent => icons[marketName(market)];
