import { type MarketIcon, marketIcon } from "@agentpit/brand/marketIcon";
import {
  Activity,
  Award,
  Biohazard,
  Bitcoin,
  Brain,
  Briefcase,
  Church,
  CircleQuestionMark,
  Clapperboard,
  CloudLightning,
  Coins,
  Cpu,
  Crown,
  FlaskConical,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  Handshake,
  HeartPulse,
  Landmark,
  type LucideIcon,
  MessageCircle,
  Music,
  Percent,
  Plane,
  Rocket,
  ScrollText,
  Ship,
  Sigma,
  Smartphone,
  Sparkles,
  Swords,
  Thermometer,
  TrendingUp,
  Trophy,
  UserMinus,
  Vote,
} from "lucide-react";

const ICONS: Readonly<Record<MarketIcon, LucideIcon>> = {
  Activity,
  Award,
  Biohazard,
  Bitcoin,
  Brain,
  Briefcase,
  Church,
  CircleQuestionMark,
  Clapperboard,
  CloudLightning,
  Coins,
  Cpu,
  Crown,
  FlaskConical,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Globe,
  Handshake,
  HeartPulse,
  Landmark,
  MessageCircle,
  Music,
  Percent,
  Plane,
  Rocket,
  ScrollText,
  Ship,
  Sigma,
  Smartphone,
  Sparkles,
  Swords,
  Thermometer,
  TrendingUp,
  Trophy,
  UserMinus,
  Vote,
};

const FRAME = "relative size-7.5 shrink-0 rounded-item bg-surface ring-1 ring-line";

export const Thumb = ({ src, title, category }: { src: string | null | undefined; title: string; category?: string | null }) => {
  if (src) return <img src={src} alt="" loading="lazy" className={`${FRAME} object-cover`} />;
  const Icon = ICONS[marketIcon({ question: title, category })];
  return (
    <span className={`${FRAME} grid place-items-center`}>
      <Icon size={14} strokeWidth={1.75} aria-hidden="true" />
    </span>
  );
};
